version: '3'
networks:
  cassandra:
services:
  cassandra:
    image: "cassandra:3.11.2"
    ports:
      - "7000"
      - "9042"
  tests:
    build: .
    links:
      - cassandra
    ports:
    - "5000:5000"